### ISSUE TITLE
Question about some functions

### ISSUE THREAD

**Issue by Arekku04** [hjfruit/react-native-printer-sunmi#2]
Hello! I am trying to make use of the library on the app I'm working with. I am using Sunmi K2 Kiosk Machine with V2 built-in printer.

Upon testing the library, I also used the sample snippets that is present on the library. However, I can't seem to change the font size of it. Also, I don't have idea which of the functions facilitates the cutting of the paper after printing.

I hope you can help me with this matter. I am willing to send other context for more clarity. Thanks!

P.S.: This is the snippet that I tried to copy on my code to test its functionality:
![image](https://github.com/24jieqi/react-native-printer-sunmi/assets/107436372/708e2e8f-0949-4321-a144-4243f6af8a56)

**Comment by Limoer96** [comment]
Almost every API has `option` parameters for customizing the printing style, and the font size is set in it. 
```typesctipt
PrinterSunmi.printText(`UserName：${data.customerName}`, {
    textSize: TEXT_FONT_SIZE,
    bold: true,
})
```
You can also use `initLine` to set the basic line style, which will take effect on each subsequent line, and the last setting will only be changed when the method is called again (unfortunately, setting the font style is not included).

About cutting of the paper, you should just call `autoOut`

If the above doesn't work please let me know, I don't have a K2 device so troubleshooting is a challenge.

**Comment by Arekku04** [comment]
This is the snippet that I tried:
```
async testPrint() {
      await PrinterSunmi.connect();
      PrinterSunmi.enableTransMode(true);
      PrinterSunmi.initLine({ align: 'CENTER' });
      PrinterSunmi.printText('Testing!', { textSize: 32, bold: true });
      PrinterSunmi.addText('Try\n', { bold: true });
      PrinterSunmi.initLine();
      PrinterSunmi.addText('Tryyyy\n');
      PrinterSunmi.printTexts([
        { text: 'Item 1', span: 2 },
        { text: 'Item 2', span: 1, style: { align: 'RIGHT' } },
        { text: 'Item 3', span: 1, style: { align: 'RIGHT' } },
      ]);
      PrinterSunmi.printTexts([
        { text: 'Item 4', span: 2 },
        { text: '22', span: 1, style: { align: 'RIGHT' } },
        { text: 'X3', span: 1, style: { align: 'RIGHT' } },
      ]);
      PrinterSunmi.printDividingLine('EMPTY', 24);
      PrinterSunmi.printDividingLine('SOLID', 2);
      PrinterSunmi.printDividingLine('EMPTY', 24);
      PrinterSunmi.printTrans();
      PrinterSunmi.autoOut();
    }
```

Upon testing `autoOut`, it doesn't cut out the paper. What could be the possible cause of it? 

Is there any troubleshooting approach that I can do in order to try to make it work?

**Comment by Limoer96** [comment]
Just call `autoOut` before commit transaction.
```
PrinterSunmi.autoOut()
PrinterSunmi.printTrans()
```
If it doesn’t work, you can consult Sunmi technical customer service.

**Comment by Arekku04** [comment]
It works now. Thanks for this! 

The only problem I'm experiencing now is the change on the properties of the printed text which I will work on investigating with.

My question this time is was there limitation on the `printBitmap()`? Like does it need limiting size and file type of the image to be printed?

By the way, thank you very much as well for accommodating my concerns. It helped me a lot on what I'm working with.

**Comment by Limoer96** [comment]
You can use common image types such as PNG, JPG, etc. It should be noted that this library does not currently support SVG. 
For the image size, it is recommended to use the same image size as the printing size. You can also set the scaling width and height through `option.witdh` and `option.height`.
