### ISSUE TITLE
你还，请问打印的时候支持汉信码生成不？

### ISSUE THREAD

**Issue by QMY-ZQ** [hjfruit/react-native-printer-sunmi#3]

**Comment by Limoer96** [comment]
你好，商米打印Android SDK没有提供任何二维码类型相关的选项，所以应该是不支持的，你可以看[文档](https://developer.sunmi.com/docs/zh-CN/xeghjk491/mafeghjk535#h-5-%E6%89%93%E5%8D%B0%E4%BA%8C%E7%BB%B4%E7%A0%81)了解更多。
